# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-22 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20180822_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinyurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
