# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-22 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20180822_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinyurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
