# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-22 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_auto_20180822_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinyurl',
            name='url',
            field=models.CharField(max_length=500, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
